openapi: 3.2.0
info:
  title: Inbox 2.0 API Reference Proactive Messaging Rest API
  description: Inbox 2.0 API Reference
  version: v1
  x-logo:
    url: static/hootsuite-logo.png
  contact:
    email: dev.support@hootsuite.com
  license:
    name: Hootsuite Developer Terms and API License Agreement
    url: https://hootsuite.com/legal/dev-api-terms
servers:
- url: https://platform.hootsuite.com
  description: Inbox 2.0 production server
security:
- bearer-token: []
tags:
- name: proactive_messaging_rest_api
  x-displayName: REST API
  description: When calling the Proactive Messaging API, the client needs to be authenticated.
paths:
  /inbox/v1/proactive-messaging:
    post:
      tags:
      - proactive_messaging_rest_api
      summary: Send proactive message
      operationId: proactiveSendMessage
      description: The message is queued for processing. Use the returned correlation id to get the status of the sent message.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendProactiveMessageRequest'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendProactiveMessageResponse'
        '400':
          description: The request is malformed.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
              example:
                errors:
                - 'channel: must not be blank'
                - 'contactReference: must not be blank'
                - 'medium: must not be null'
                - 'text: must not be blank'
        '401':
          description: 'Unauthorized: when using an invalid or expired access token

            '
  /inbox/v1/proactive-messaging/{correlationId}:
    get:
      tags:
      - proactive_messaging_rest_api
      summary: Get status
      operationId: proactiveGetStatusForCorrelationId
      description: Get the status overview for a sent proactive message
      parameters:
      - in: path
        name: correlationId
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusOverviewResponse'
        '400':
          description: The request is malformed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                errors:
                - Nothing found for this correlation id
        '401':
          description: 'Unauthorized: when using an invalid or expired access token

            '
  /inbox/v1/proactive-messaging/{correlationId}/{status}:
    get:
      tags:
      - proactive_messaging_rest_api
      summary: Get status detail
      operationId: proactiveGetStatusDetailForCorrelationId
      description: Get the details of a message with a specific status.
      parameters:
      - in: path
        name: correlationId
        schema:
          type: string
        required: true
      - in: path
        name: status
        schema:
          type: string
          enum:
          - PROCESSING
          - FAILED
          - SENT
          - DELIVERED
          - DELIVERING_FAILED
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusDetailResponse'
        '400':
          description: The request is malformed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                errors:
                - Nothing found for this correlation id
        '401':
          description: 'Unauthorized: when using an invalid or expired access token

            '
components:
  schemas:
    SendProactiveMessageResponse:
      type: object
      properties:
        correlationId:
          type: string
          example: 4f1dba7b-9ef3-11e8-a0f4-175408e41992
    StatusOverviewResponse:
      type: object
      properties:
        correlationId:
          type: string
          description: The correlation id of the sent message.
        total:
          type: string
          description: The total number of sent proactive messages.
        statuses:
          type: object
          description: An overview with the number of messages per status
          properties:
            PROCESSING:
              type: number
              description: Number of proactive messages that are queued for sending.
            FAILED:
              type: number
              description: Number of proactive messages that failed to send.
            SENT:
              type: number
              description: Number of proactive messages that are sent.
            DELIVERED:
              type: number
              description: Number of proactive messages that are sent and delivered.
            DELIVERING_FAILED:
              type: number
              description: Number of proactive messages that are sent but could not be delivered.
      example:
        correlationId: 44717822-9f05-11e8-b71e-671342217f40
        total: 1
        statuses:
          DELIVERED: 1
    SendProactiveMessageRequest:
      type: object
      properties:
        medium:
          type: string
          description: The medium you want to use
          enum:
          - WHATSAPP
        channel:
          type: string
          description: The name of the channel. Use one of the Accounts in Settings -> Channels
        contact:
          type: string
          description: The reference to a contact. In case of a telephone number it should start with a plus sign
        text:
          type: string
          description: The message you want to send
        metadata:
          type: object
          additionalProperties:
            type: string
          example:
            myReference: '19758293529351'
          description: 'When sending a proactive message, you can pass along custom information that is stored in Inbox 2.0. This data can then be exported. Please contact `dev.support@hootsuite.com` to add metadata to the Messages export. For example, when you send an appointment confirmation to your customer, you can pass along a unique identifier. You can then download the Messages export from Inbox 2.0, and determine how many unique customers are responding to your outbound notification.

            '
        sender:
          type: object
          properties:
            pictureUrl:
              type: string
              example: https://example.com/my-picture.png
              description: 'The url of the picture to be used as the sender''s avatar.

                '
      required:
      - medium
      - channel
      - contact
      - text
    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
    StatusDetailResponse:
      type: array
      items:
        type: object
        properties:
          status:
            type: string
            description: The status of the message
          contact:
            type: string
            description: The contact used to send the message to
          reason:
            type: string
            description: The reason of failure
      example:
      - status: FAILED
        contact: '+32495123456'
        reason: No channel found for medium WHATSAPP
  securitySchemes:
    bearer-token:
      type: http
      scheme: bearer
    basic-auth:
      type: http
      scheme: basic
    Oauth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: TO_BE_CONFIGURED_IN_INBOX_2_0
          scopes:
            some_scope: TO_BE_CONFIGURED_IN_INBOX_2_0
    SharedSecret:
      type: apiKey
      in: header
      name: X-Hootsuite-Signature
x-tagGroups:
- name: General
  tags:
  - rest-api-authentication
- name: CRM API
  tags:
  - crm_introduction
  - crm_webhooks
  - crm_rest_api
- name: Virtual Agent API
  tags:
  - vai_introduction
  - vai_webhooks
  - vai_rest_api
- name: Real-time metrics API
  tags:
  - real_time_metrics_introduction
  - real_time_metrics_rest_api
- name: User Presence API
  tags:
  - user_presence_introduction
  - user_presence_rest_api
- name: Queue API
  tags:
  - queue_introduction
  - queue_rest_api
- name: Proactive messaging API
  tags:
  - proactive_messaging_introduction
  - proactive_messaging_rest_api
- name: Messenger SDK
  tags:
  - messenger_introduction
  - messenger_web_sdk
